wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1673444501.320914
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      2:
      - 1
      - 41
      - 50
      - 55
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.13.8
      8:
      - 5
batch_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.475198917213748
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.001
