name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "$" | docker login \
          -u "$" --password-stdin docker.io
        docker build . --file trainer.dockerfile \
          --tag docker.io/$/$:$GITHUB_SHA
        docker build . --file predict.dockerfile \
          --tag docker.io/$/$:$GITHUB_SHA
        docker push docker.io/$/$:$GITHUB_SHA
